extern crate phf_codegen;

use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

const BOOLEAN: &'static [&'static str] = &[
	"auto_left_margin", "auto_right_margin", "no_esc_ctlc", "ceol_standout_glitch",
	"eat_newline_glitch", "erase_overstrike", "generic_type", "hard_copy", "has_meta_key",
	"has_status_line", "insert_null_glitch", "memory_above", "memory_below", "move_insert_mode",
	"move_standout_mode", "over_strike", "status_line_esc_ok", "dest_tabs_magic_smso",
	"tilde_glitch", "transparent_underline", "xon_xoff", "needs_xon_xoff", "prtr_silent",
	"hard_cursor", "non_rev_rmcup", "no_pad_char", "non_dest_scroll_region", "can_change",
	"back_color_erase", "hue_lightness_saturation", "col_addr_glitch", "cr_cancels_micro_mode",
	"has_print_wheel", "row_addr_glitch", "semi_auto_right_margin", "cpi_changes_res",
	"lpi_changes_res", "backspaces_with_bs", "crt_no_scrolling", "no_correctly_working_cr",
	"gnu_has_meta_key", "linefeed_is_newline", "has_hardware_tabs", "return_does_clr_eol"
];

const NUMBER: &'static [&'static str] = &[
	"columns", "init_tabs", "lines", "lines_of_memory", "magic_cookie_glitch", "padding_baud_rate",
	"virtual_terminal", "width_status_line", "num_labels", "label_height", "label_width",
	"max_attributes", "maximum_windows", "max_colors", "max_pairs", "no_color_video",
	"buffer_capacity", "dot_vert_spacing", "dot_horz_spacing", "max_micro_address",
	"max_micro_jump", "micro_col_size", "micro_line_size", "number_of_pins", "output_res_char",
	"output_res_line", "output_res_horz_inch", "output_res_vert_inch", "print_rate",
	"wide_char_size", "buttons", "bit_image_entwining", "bit_image_type", "magic_cookie_glitch_ul",
	"carriage_return_delay", "new_line_delay", "backspace_delay", "horizontal_tab_delay",
	"number_of_function_keys"
];

const STRING: &'static [&'static str] = &[
	"back_tab", "bell", "carriage_return", "change_scroll_region", "clear_all_tabs",
	"clear_screen", "clr_eol", "clr_eos", "column_address", "command_character", "cursor_address",
	"cursor_down", "cursor_home", "cursor_invisible", "cursor_left", "cursor_mem_address",
	"cursor_normal", "cursor_right", "cursor_to_ll", "cursor_up", "cursor_visible",
	"delete_character", "delete_line", "dis_status_line", "down_half_line",
	"enter_alt_charset_mode", "enter_blink_mode", "enter_bold_mode", "enter_ca_mode",
	"enter_delete_mode", "enter_dim_mode", "enter_insert_mode", "enter_secure_mode",
	"enter_protected_mode", "enter_reverse_mode", "enter_standout_mode", "enter_underline_mode",
	"erase_chars", "exit_alt_charset_mode", "exit_attribute_mode", "exit_ca_mode",
	"exit_delete_mode", "exit_insert_mode", "exit_standout_mode", "exit_underline_mode",
	"flash_screen", "form_feed", "from_status_line", "init_1string", "init_2string",
	"init_3string", "init_file", "insert_character", "insert_line", "insert_padding",
	"key_backspace", "key_catab", "key_clear", "key_ctab", "key_dc", "key_dl", "key_down",
	"key_eic", "key_eol", "key_eos", "key_f0", "key_f1", "key_f10", "key_f2", "key_f3", "key_f4",
	"key_f5", "key_f6", "key_f7", "key_f8", "key_f9", "key_home", "key_ic", "key_il", "key_left",
	"key_ll", "key_npage", "key_ppage", "key_right", "key_sf", "key_sr", "key_stab", "key_up",
	"keypad_local", "keypad_xmit", "lab_f0", "lab_f1", "lab_f10", "lab_f2", "lab_f3", "lab_f4",
	"lab_f5", "lab_f6", "lab_f7", "lab_f8", "lab_f9", "meta_off", "meta_on", "newline", "pad_char",
	"parm_dch", "parm_delete_line", "parm_down_cursor", "parm_ich", "parm_index",
	"parm_insert_line", "parm_left_cursor", "parm_right_cursor", "parm_rindex", "parm_up_cursor",
	"pkey_key", "pkey_local", "pkey_xmit", "print_screen", "prtr_off", "prtr_on", "repeat_char",
	"reset_1string", "reset_2string", "reset_3string", "reset_file", "restore_cursor",
	"row_address", "save_cursor", "scroll_forward", "scroll_reverse", "set_attributes", "set_tab",
	"set_window", "tab", "to_status_line", "underline_char", "up_half_line", "init_prog", "key_a1",
	"key_a3", "key_b2", "key_c1", "key_c3", "prtr_non", "char_padding", "acs_chars", "plab_norm",
	"key_btab", "enter_xon_mode", "exit_xon_mode", "enter_am_mode", "exit_am_mode",
	"xon_character", "xoff_character", "ena_acs", "label_on", "label_off", "key_beg", "key_cancel",
	"key_close", "key_command", "key_copy", "key_create", "key_end", "key_enter", "key_exit",
	"key_find", "key_help", "key_mark", "key_message", "key_move", "key_next", "key_open",
	"key_options", "key_previous", "key_print", "key_redo", "key_reference", "key_refresh",
	"key_replace", "key_restart", "key_resume", "key_save", "key_suspend", "key_undo", "key_sbeg",
	"key_scancel", "key_scommand", "key_scopy", "key_screate", "key_sdc", "key_sdl", "key_select",
	"key_send", "key_seol", "key_sexit", "key_sfind", "key_shelp", "key_shome", "key_sic",
	"key_sleft", "key_smessage", "key_smove", "key_snext", "key_soptions", "key_sprevious",
	"key_sprint", "key_sredo", "key_sreplace", "key_sright", "key_srsume", "key_ssave",
	"key_ssuspend", "key_sundo", "req_for_input", "key_f11", "key_f12", "key_f13", "key_f14",
	"key_f15", "key_f16", "key_f17", "key_f18", "key_f19", "key_f20", "key_f21", "key_f22",
	"key_f23", "key_f24", "key_f25", "key_f26", "key_f27", "key_f28", "key_f29", "key_f30",
	"key_f31", "key_f32", "key_f33", "key_f34", "key_f35", "key_f36", "key_f37", "key_f38",
	"key_f39", "key_f40", "key_f41", "key_f42", "key_f43", "key_f44", "key_f45", "key_f46",
	"key_f47", "key_f48", "key_f49", "key_f50", "key_f51", "key_f52", "key_f53", "key_f54",
	"key_f55", "key_f56", "key_f57", "key_f58", "key_f59", "key_f60", "key_f61", "key_f62",
	"key_f63", "clr_bol", "clear_margins", "set_left_margin", "set_right_margin", "label_format",
	"set_clock", "display_clock", "remove_clock", "create_window", "goto_window", "hangup",
	"dial_phone", "quick_dial", "tone", "pulse", "flash_hook", "fixed_pause", "wait_tone", "user0",
	"user1", "user2", "user3", "user4", "user5", "user6", "user7", "user8", "user9", "orig_pair",
	"orig_colors", "initialize_color", "initialize_pair", "set_color_pair", "set_foreground",
	"set_background", "change_char_pitch", "change_line_pitch", "change_res_horz",
	"change_res_vert", "define_char", "enter_doublewide_mode", "enter_draft_quality",
	"enter_italics_mode", "enter_leftward_mode", "enter_micro_mode", "enter_near_letter_quality",
	"enter_normal_quality", "enter_shadow_mode", "enter_subscript_mode", "enter_superscript_mode",
	"enter_upward_mode", "exit_doublewide_mode", "exit_italics_mode", "exit_leftward_mode",
	"exit_micro_mode", "exit_shadow_mode", "exit_subscript_mode", "exit_superscript_mode",
	"exit_upward_mode", "micro_column_address", "micro_down", "micro_left", "micro_right",
	"micro_row_address", "micro_up", "order_of_pins", "parm_down_micro", "parm_left_micro",
	"parm_right_micro", "parm_up_micro", "select_char_set", "set_bottom_margin",
	"set_bottom_margin_parm", "set_left_margin_parm", "set_right_margin_parm", "set_top_margin",
	"set_top_margin_parm", "start_bit_image", "start_char_set_def", "stop_bit_image",
	"stop_char_set_def", "subscript_characters", "superscript_characters", "these_cause_cr",
	"zero_motion", "char_set_names", "key_mouse", "mouse_info", "req_mouse_pos", "get_mouse",
	"set_a_foreground", "set_a_background", "pkey_plab", "device_type", "code_set_init",
	"set0_des_seq", "set1_des_seq", "set2_des_seq", "set3_des_seq", "set_lr_margin",
	"set_tb_margin", "bit_image_repeat", "bit_image_newline", "bit_image_carriage_return",
	"color_names", "define_bit_image_region", "end_bit_image_region", "set_color_band",
	"set_page_length", "display_pc_char", "enter_pc_charset_mode", "exit_pc_charset_mode",
	"enter_scancode_mode", "exit_scancode_mode", "pc_term_options", "scancode_escape",
	"alt_scancode_esc", "enter_horizontal_hl_mode", "enter_left_hl_mode", "enter_low_hl_mode",
	"enter_right_hl_mode", "enter_top_hl_mode", "enter_vertical_hl_mode", "set_a_attributes",
	"set_pglen_inch", "termcap_init2", "termcap_reset", "linefeed_if_not_lf",
	"backspace_if_not_bs", "other_non_function_keys", "arrow_key_map", "acs_ulcorner",
	"acs_llcorner", "acs_urcorner", "acs_lrcorner", "acs_ltee", "acs_rtee", "acs_btee", "acs_ttee",
	"acs_hline", "acs_vline", "acs_plus", "memory_lock", "memory_unlock", "box_chars_1"
];

const ALIASES: &'static [(&'static str, &'static str)] = &[
	// Boolean names from termcap.
	("bw", "auto_left_margin"),
	("am", "auto_right_margin"),
	("xsb", "no_esc_ctlc"),
	("xhp", "ceol_standout_glitch"),
	("xenl", "eat_newline_glitch"),
	("eo", "erase_overstrike"),
	("gn", "generic_type"),
	("hc", "hard_copy"),
	("km", "has_meta_key"),
	("hs", "has_status_line"),
	("in", "insert_null_glitch"),
	("db", "memory_above"),
	("da", "memory_below"),
	("mir", "move_insert_mode"),
	("msgr", "move_standout_mode"),
	("os", "over_strike"),
	("eslok", "status_line_esc_ok"),
	("xt", "dest_tabs_magic_smso"),
	("hz", "tilde_glitch"),
	("ul", "transparent_underline"),
	("xon", "xon_xoff"),
	("nxon", "needs_xon_xoff"),
	("mc5i", "prtr_silent"),
	("chts", "hard_cursor"),
	("nrrmc", "non_rev_rmcup"),
	("npc", "no_pad_char"),
	("ndscr", "non_dest_scroll_region"),
	("ccc", "can_change"),
	("bce", "back_color_erase"),
	("hls", "hue_lightness_saturation"),
	("xhpa", "col_addr_glitch"),
	("crxm", "cr_cancels_micro_mode"),
	("daisy", "has_print_wheel"),
	("xvpa", "row_addr_glitch"),
	("sam", "semi_auto_right_margin"),
	("cpix", "cpi_changes_res"),
	("lpix", "lpi_changes_res"),
	("OTns", "crt_no_scrolling"),
	("OTnc", "no_correctly_working_cr"),
	("OTMT", "gnu_has_meta_key"),
	("OTNL", "linefeed_is_newline"),
	("OTpt", "has_hardware_tabs"),
	("OTxr", "return_does_clr_eol"),

	// Number names from termcap.
	("cols", "columns"),
	("it", "init_tabs"),
	("lines", "lines"),
	("lm", "lines_of_memory"),
	("xmc", "magic_cookie_glitch"),
	("pb", "padding_baud_rate"),
	("vt", "virtual_terminal"),
	("wsl", "width_status_line"),
	("nlab", "num_labels"),
	("lh", "label_height"),
	("lw", "label_width"),
	("ma", "max_attributes"),
	("wnum", "maximum_windows"),
	("colors", "max_colors"),
	("pairs", "max_pairs"),
	("ncv", "no_color_video"),
	("bufsz", "buffer_capacity"),
	("spinv", "dot_vert_spacing"),
	("spinh", "dot_horz_spacing"),
	("maddr", "max_micro_address"),
	("mjump", "max_micro_jump"),
	("mcs", "micro_col_size"),
	("mls", "micro_line_size"),
	("npins", "number_of_pins"),
	("orc", "output_res_char"),
	("orl", "output_res_line"),
	("orhi", "output_res_horz_inch"),
	("orvi", "output_res_vert_inch"),
	("cps", "print_rate"),
	("widcs", "wide_char_size"),
	("btns", "buttons"),
	("bitwin", "bit_image_entwining"),
	("bitype", "bit_image_type"),
	("UTug", "magic_cookie_glitch_ul"),
	("OTdC", "carriage_return_delay"),
	("OTdN", "new_line_delay"),
	("OTdB", "backspace_delay"),
	("OTdT", "horizontal_tab_delay"),
	("OTkn", "number_of_function_keys"),

	// String names from termcap.
	("cbt", "back_tab"),
	("cr", "carriage_return"),
	("csr", "change_scroll_region"),
	("tbc", "clear_all_tabs"),
	("clear", "clear_screen"),
	("hpa", "column_address"),
	("cmdch", "command_character"),
	("cup", "cursor_address"),
	("cud1", "cursor_down"),
	("home", "cursor_home"),
	("civis", "cursor_invisible"),
	("cub1", "cursor_left"),
	("mrcup", "cursor_mem_address"),
	("cnorm", "cursor_normal"),
	("cuf1", "cursor_right"),
	("ll", "cursor_to_ll"),
	("cuu1", "cursor_up"),
	("cvvis", "cursor_visible"),
	("dch1", "delete_character"),
	("dl1", "delete_line"),
	("dsl", "dis_status_line"),
	("hd", "down_half_line"),
	("smacs", "enter_alt_charset_mode"),
	("blink", "enter_blink_mode"),
	("bold", "enter_bold_mode"),
	("smcup", "enter_ca_mode"),
	("smdc", "enter_delete_mode"),
	("dim", "enter_dim_mode"),
	("smir", "enter_insert_mode"),
	("invis", "enter_secure_mode"),
	("prot", "enter_protected_mode"),
	("rev", "enter_reverse_mode"),
	("smso", "enter_standout_mode"),
	("smul", "enter_underline_mode"),
	("ech", "erase_chars"),
	("rmacs", "exit_alt_charset_mode"),
	("sgr0", "exit_attribute_mode"),
	("rmcup", "exit_ca_mode"),
	("rmdc", "exit_delete_mode"),
	("rmir", "exit_insert_mode"),
	("rmso", "exit_standout_mode"),
	("rmul", "exit_underline_mode"),
	("flash", "flash_screen"),
	("ff", "form_feed"),
	("fsl", "from_status_line"),
	("is1", "init_1string"),
	("is2", "init_2string"),
	("is3", "init_3string"),
	("if", "init_file"),
	("ich1", "insert_character"),
	("il1", "insert_line"),
	("ip", "insert_padding"),
	("kbs", "key_backspace"),
	("ktbc", "key_catab"),
	("kclr", "key_clear"),
	("kctab", "key_ctab"),
	("kcud1", "key_down"),
	("khome", "key_home"),
	("kcub1", "key_left"),
	("knp", "key_npage"),
	("kpp", "key_ppage"),
	("kcuf1", "key_right"),
	("khts", "key_stab"),
	("rmkx", "keypad_local"),
	("smkx", "keypad_xmit"),
	("rmm", "meta_off"),
	("pad", "pad_char"),
	("dch", "parm_dch"),
	("dl", "parm_delete_line"),
	("cud", "parm_down_cursor"),
	("ich", "parm_ich"),
	("indn", "parm_index"),
	("il", "parm_insert_line"),
	("cub", "parm_left_cursor"),
	("cuf", "parm_right_cursor"),
	("rin", "parm_rindex"),
	("cuu", "parm_up_cursor"),
	("pfkey", "pkey_key"),
	("pfloc", "pkey_local"),
	("pfx", "pkey_xmit"),
	("mc0", "print_screen"),
	("mc4", "prtr_off"),
	("rep", "repeat_char"),
	("rs1", "reset_1string"),
	("rs2", "reset_2string"),
	("rs3", "reset_3string"),
	("rf", "reset_file"),
	("rc", "restore_cursor"),
	("vpa", "row_address"),
	("sc", "save_cursor"),
	("ind", "scroll_forward"),
	("ri", "scroll_reverse"),
	("sgr", "set_attributes"),
	("wind", "set_window"),
	("tsl", "to_status_line"),
	("uc", "underline_char"),
	("hu", "up_half_line"),
	("iprog", "init_prog"),
	("mc5p", "prtr_non"),
	("rmp", "char_padding"),
	("acsc", "acs_chars"),
	("pln", "plab_norm"),
	("kcbt", "key_btab"),
	("smxon", "enter_xon_mode"),
	("rmxon", "exit_xon_mode"),
	("smam", "enter_am_mode"),
	("rmam", "exit_am_mode"),
	("xonc", "xon_character"),
	("xoffc", "xoff_character"),
	("smln", "label_on"),
	("rmln", "label_off"),
	("kcan", "key_cancel"),
	("kclo", "key_close"),
	("kcmd", "key_command"),
	("kcpy", "key_copy"),
	("kcrt", "key_create"),
	("kent", "key_enter"),
	("kext", "key_exit"),
	("kfnd", "key_find"),
	("khlp", "key_help"),
	("kmrk", "key_mark"),
	("kmsg", "key_message"),
	("kmov", "key_move"),
	("knxt", "key_next"),
	("kopn", "key_open"),
	("kopt", "key_options"),
	("kprv", "key_previous"),
	("kprt", "key_print"),
	("krdo", "key_redo"),
	("kref", "key_reference"),
	("krfr", "key_refresh"),
	("krpl", "key_replace"),
	("krst", "key_restart"),
	("kres", "key_resume"),
	("ksav", "key_save"),
	("kspd", "key_suspend"),
	("kund", "key_undo"),
	("kBEG", "key_sbeg"),
	("kCAN", "key_scancel"),
	("kCMD", "key_scommand"),
	("kCPY", "key_scopy"),
	("kCRT", "key_screate"),
	("kslt", "key_select"),
	("kEND", "key_send"),
	("kEOL", "key_seol"),
	("kEXT", "key_sexit"),
	("kFND", "key_sfind"),
	("kHLP", "key_shelp"),
	("kHOM", "key_shome"),
	("kLFT", "key_sleft"),
	("kMSG", "key_smessage"),
	("kMOV", "key_smove"),
	("kNXT", "key_snext"),
	("kOPT", "key_soptions"),
	("kPRV", "key_sprevious"),
	("kPRT", "key_sprint"),
	("kRDO", "key_sredo"),
	("kRPL", "key_sreplace"),
	("kRIT", "key_sright"),
	("kRES", "key_srsume"),
	("kSAV", "key_ssave"),
	("kSPD", "key_ssuspend"),
	("kUND", "key_sundo"),
	("rfi", "req_for_input"),
	("dclk", "display_clock"),
	("rmclk", "remove_clock"),
	("cwin", "create_window"),
	("wingo", "goto_window"),
	("dial", "dial_phone"),
	("qdial", "quick_dial"),
	("hook", "flash_hook"),
	("pause", "fixed_pause"),
	("wait", "wait_tone"),
	("op", "orig_pair"),
	("oc", "orig_colors"),
	("initc", "initialize_color"),
	("initp", "initialize_pair"),
	("scp", "set_color_pair"),
	("setf", "set_foreground"),
	("setb", "set_background"),
	("cpi", "change_char_pitch"),
	("lpi", "change_line_pitch"),
	("chr", "change_res_horz"),
	("cvr", "change_res_vert"),
	("defc", "define_char"),
	("swidm", "enter_doublewide_mode"),
	("sdrfq", "enter_draft_quality"),
	("sitm", "enter_italics_mode"),
	("slm", "enter_leftward_mode"),
	("smicm", "enter_micro_mode"),
	("snlq", "enter_near_letter_quality"),
	("snrmq", "enter_normal_quality"),
	("sshm", "enter_shadow_mode"),
	("ssubm", "enter_subscript_mode"),
	("ssupm", "enter_superscript_mode"),
	("sum", "enter_upward_mode"),
	("rwidm", "exit_doublewide_mode"),
	("ritm", "exit_italics_mode"),
	("rlm", "exit_leftward_mode"),
	("rmicm", "exit_micro_mode"),
	("rshm", "exit_shadow_mode"),
	("rsubm", "exit_subscript_mode"),
	("rsupm", "exit_superscript_mode"),
	("rum", "exit_upward_mode"),
	("mhpa", "micro_column_address"),
	("mcud1", "micro_down"),
	("mcub1", "micro_left"),
	("mcuf1", "micro_right"),
	("mvpa", "micro_row_address"),
	("mcuu1", "micro_up"),
	("porder", "order_of_pins"),
	("mcud", "parm_down_micro"),
	("mcub", "parm_left_micro"),
	("mcuf", "parm_right_micro"),
	("mcuu", "parm_up_micro"),
	("scs", "select_char_set"),
	("smgb", "set_bottom_margin"),
	("smgbp", "set_bottom_margin_parm"),
	("smglp", "set_left_margin_parm"),
	("smgrp", "set_right_margin_parm"),
	("smgt", "set_top_margin"),
	("smgtp", "set_top_margin_parm"),
	("sbim", "start_bit_image"),
	("scsd", "start_char_set_def"),
	("rbim", "stop_bit_image"),
	("rcsd", "stop_char_set_def"),
	("subcs", "subscript_characters"),
	("supcs", "superscript_characters"),
	("docr", "these_cause_cr"),
	("zerom", "zero_motion"),
	("csnm", "char_set_names"),
	("kmous", "key_mouse"),
	("minfo", "mouse_info"),
	("reqmp", "req_mouse_pos"),
	("getm", "get_mouse"),
	("setaf", "set_a_foreground"),
	("setab", "set_a_background"),
	("pfxl", "pkey_plab"),
	("devt", "device_type"),
	("csin", "code_set_init"),
	("s0ds", "set0_des_seq"),
	("s1ds", "set1_des_seq"),
	("s2ds", "set2_des_seq"),
	("s3ds", "set3_des_seq"),
	("smglr", "set_lr_margin"),
	("smgtb", "set_tb_margin"),
	("birep", "bit_image_repeat"),
	("binel", "bit_image_newline"),
	("bicr", "bit_image_carriage_return"),
	("colornm", "color_names"),
	("defbi", "define_bit_image_region"),
	("endbi", "end_bit_image_region"),
	("setcolor", "set_color_band"),
	("slines", "set_page_length"),
	("dispc", "display_pc_char"),
	("smpch", "enter_pc_charset_mode"),
	("rmpch", "exit_pc_charset_mode"),
	("smsc", "enter_scancode_mode"),
	("rmsc", "exit_scancode_mode"),
	("pctrm", "pc_term_options"),
	("scesc", "scancode_escape"),
	("scesa", "alt_scancode_esc"),
	("ehhlm", "enter_horizontal_hl_mode"),
	("elhlm", "enter_left_hl_mode"),
	("elohlm", "enter_low_hl_mode"),
	("erhlm", "enter_right_hl_mode"),
	("ethlm", "enter_top_hl_mode"),
	("evhlm", "enter_vertical_hl_mode"),
	("sgr1", "set_a_attributes"),
	("slength", "set_pglen_inch"),
	("OTi2", "termcap_init2"),
	("OTrs", "termcap_reset"),
	("OTnl", "linefeed_if_not_lf"),
	("OTbs", "backspace_if_not_bs"),
	("OTko", "other_non_function_keys"),
	("OTma", "arrow_key_map"),
	("OTG2", "acs_ulcorner"),
	("OTG3", "acs_llcorner"),
	("OTG1", "acs_urcorner"),
	("OTG4", "acs_lrcorner"),
	("OTGR", "acs_ltee"),
	("OTGL", "acs_rtee"),
	("OTGU", "acs_btee"),
	("OTGD", "acs_ttee"),
	("OTGH", "acs_hline"),
	("OTGV", "acs_vline"),
	("OTGC", "acs_plus"),
	("meml", "memory_lock"),
	("memu", "memory_unlock"),
	("box1", "box_chars_1"),

	// Boolean names from tcap.
	("ut", "back_color_erase"),
	("cc", "can_change"),
	("xs", "ceol_standout_glitch"),
	("YA", "col_addr_glitch"),
	("YF", "cpi_changes_res"),
	("YB", "cr_cancels_micro_mode"),
	("xn", "eat_newline_glitch"),
	("HC", "hard_cursor"),
	("YC", "has_print_wheel"),
	("hl", "hue_lightness_saturation"),
	("YG", "lpi_changes_res"),
	("mi", "move_insert_mode"),
	("ms", "move_standout_mode"),
	("nx", "needs_xon_xoff"),
	("xb", "no_esc_ctlc"),
	("NP", "no_pad_char"),
	("ND", "non_dest_scroll_region"),
	("NR", "non_rev_rmcup"),
	("5i", "prtr_silent"),
	("YD", "row_addr_glitch"),
	("YE", "semi_auto_right_margin"),
	("es", "status_line_esc_ok"),
	("xo", "xon_xoff"),

	// Number names from tcap.
	("co", "columns"),
	("li", "lines"),
	("sg", "magic_cookie_glitch"),
	("Co", "max_colors"),
	("pa", "max_pairs"),
	("MW", "maximum_windows"),
	("NC", "no_color_video"),
	("Nl", "num_labels"),
	("ws", "width_status_line"),
	("Yo", "bit_image_entwining"),
	("Yp", "bit_image_type"),
	("Ya", "buffer_capacity"),
	("BT", "buttons"),
	("Yc", "dot_horz_spacing"),
	("Yb", "dot_vert_spacing"),
	("Yd", "max_micro_address"),
	("Ye", "max_micro_jump"),
	("Yf", "micro_col_size"),
	("Yg", "micro_line_size"),
	("Yh", "number_of_pins"),
	("Yi", "output_res_char"),
	("Yk", "output_res_horz_inch"),
	("Yj", "output_res_line"),
	("Yl", "output_res_vert_inch"),
	("Ym", "print_rate"),
	("Yn", "wide_char_size"),

	// String names from tcap.
	("ac", "acs_chars"),
	("bt", "back_tab"),
	("bl", "bell"),
	("ZA", "change_char_pitch"),
	("ZB", "change_line_pitch"),
	("ZC", "change_res_horz"),
	("ZD", "change_res_vert"),
	("cs", "change_scroll_region"),
	("rP", "char_padding"),
	("ct", "clear_all_tabs"),
	("MC", "clear_margins"),
	("cl", "clear_screen"),
	("cb", "clr_bol"),
	("ce", "clr_eol"),
	("cd", "clr_eos"),
	("ch", "column_address"),
	("CC", "command_character"),
	("CW", "create_window"),
	("cm", "cursor_address"),
	("do", "cursor_down"),
	("ho", "cursor_home"),
	("vi", "cursor_invisible"),
	("le", "cursor_left"),
	("CM", "cursor_mem_address"),
	("ve", "cursor_normal"),
	("nd", "cursor_right"),
	("up", "cursor_up"),
	("vs", "cursor_visible"),
	("ZE", "define_char"),
	("dc", "delete_character"),
	("DI", "dial_phone"),
	("ds", "dis_status_line"),
	("DK", "display_clock"),
	("eA", "ena_acs"),
	("as", "enter_alt_charset_mode"),
	("SA", "enter_am_mode"),
	("mb", "enter_blink_mode"),
	("md", "enter_bold_mode"),
	("ti", "enter_ca_mode"),
	("dm", "enter_delete_mode"),
	("mh", "enter_dim_mode"),
	("ZF", "enter_doublewide_mode"),
	("ZG", "enter_draft_quality"),
	("im", "enter_insert_mode"),
	("ZH", "enter_italics_mode"),
	("ZI", "enter_leftward_mode"),
	("ZJ", "enter_micro_mode"),
	("ZK", "enter_near_letter_quality"),
	("ZL", "enter_normal_quality"),
	("mp", "enter_protected_mode"),
	("mr", "enter_reverse_mode"),
	("mk", "enter_secure_mode"),
	("ZM", "enter_shadow_mode"),
	("so", "enter_standout_mode"),
	("ZN", "enter_subscript_mode"),
	("ZO", "enter_superscript_mode"),
	("us", "enter_underline_mode"),
	("ZP", "enter_upward_mode"),
	("SX", "enter_xon_mode"),
	("ec", "erase_chars"),
	("ae", "exit_alt_charset_mode"),
	("RA", "exit_am_mode"),
	("me", "exit_attribute_mode"),
	("te", "exit_ca_mode"),
	("ed", "exit_delete_mode"),
	("ZQ", "exit_doublewide_mode"),
	("ei", "exit_insert_mode"),
	("ZR", "exit_italics_mode"),
	("ZS", "exit_leftward_mode"),
	("ZT", "exit_micro_mode"),
	("ZU", "exit_shadow_mode"),
	("se", "exit_standout_mode"),
	("ZV", "exit_subscript_mode"),
	("ZW", "exit_superscript_mode"),
	("ue", "exit_underline_mode"),
	("ZX", "exit_upward_mode"),
	("RX", "exit_xon_mode"),
	("PA", "fixed_pause"),
	("fh", "flash_hook"),
	("vb", "flash_screen"),
	("fs", "from_status_line"),
	("WG", "goto_window"),
	("HU", "hangup"),
	("i1", "init_1string"),
	("is", "init_2string"),
	("i3", "init_3string"),
	("iP", "init_prog"),
	("Ic", "initialize_color"),
	("Ip", "initialize_pair"),
	("ic", "insert_character"),
	("al", "insert_line"),
	("K1", "key_a1"),
	("K3", "key_a3"),
	("K2", "key_b2"),
	("kb", "key_backspace"),
	("@1", "key_beg"),
	("kB", "key_btab"),
	("K4", "key_c1"),
	("K5", "key_c3"),
	("@2", "key_cancel"),
	("ka", "key_catab"),
	("kC", "key_clear"),
	("@3", "key_close"),
	("@4", "key_command"),
	("@5", "key_copy"),
	("@6", "key_create"),
	("kt", "key_ctab"),
	("kD", "key_dc"),
	("kL", "key_dl"),
	("kd", "key_down"),
	("kM", "key_eic"),
	("@7", "key_end"),
	("@8", "key_enter"),
	("kE", "key_eol"),
	("kS", "key_eos"),
	("@9", "key_exit"),
	("k0", "key_f0"),
	("k1", "key_f1"),
	("k;", "key_f10"),
	("F1", "key_f11"),
	("F2", "key_f12"),
	("F3", "key_f13"),
	("F4", "key_f14"),
	("F5", "key_f15"),
	("F6", "key_f16"),
	("F7", "key_f17"),
	("F8", "key_f18"),
	("F9", "key_f19"),
	("k2", "key_f2"),
	("FA", "key_f20"),
	("FB", "key_f21"),
	("FC", "key_f22"),
	("FD", "key_f23"),
	("FE", "key_f24"),
	("FF", "key_f25"),
	("FG", "key_f26"),
	("FH", "key_f27"),
	("FI", "key_f28"),
	("FJ", "key_f29"),
	("k3", "key_f3"),
	("FK", "key_f30"),
	("FL", "key_f31"),
	("FM", "key_f32"),
	("FN", "key_f33"),
	("FO", "key_f34"),
	("FP", "key_f35"),
	("FQ", "key_f36"),
	("FR", "key_f37"),
	("FS", "key_f38"),
	("FT", "key_f39"),
	("k4", "key_f4"),
	("FU", "key_f40"),
	("FV", "key_f41"),
	("FW", "key_f42"),
	("FX", "key_f43"),
	("FY", "key_f44"),
	("FZ", "key_f45"),
	("Fa", "key_f46"),
	("Fb", "key_f47"),
	("Fc", "key_f48"),
	("Fd", "key_f49"),
	("k5", "key_f5"),
	("Fe", "key_f50"),
	("Ff", "key_f51"),
	("Fg", "key_f52"),
	("Fh", "key_f53"),
	("Fi", "key_f54"),
	("Fj", "key_f55"),
	("Fk", "key_f56"),
	("Fl", "key_f57"),
	("Fm", "key_f58"),
	("Fn", "key_f59"),
	("k6", "key_f6"),
	("Fo", "key_f60"),
	("Fp", "key_f61"),
	("Fq", "key_f62"),
	("Fr", "key_f63"),
	("k7", "key_f7"),
	("k8", "key_f8"),
	("k9", "key_f9"),
	("@0", "key_find"),
	("%1", "key_help"),
	("kh", "key_home"),
	("kI", "key_ic"),
	("kA", "key_il"),
	("kl", "key_left"),
	("kH", "key_ll"),
	("%2", "key_mark"),
	("%3", "key_message"),
	("%4", "key_move"),
	("%5", "key_next"),
	("kN", "key_npage"),
	("%6", "key_open"),
	("%7", "key_options"),
	("kP", "key_ppage"),
	("%8", "key_previous"),
	("%9", "key_print"),
	("%0", "key_redo"),
	("&1", "key_reference"),
	("&2", "key_refresh"),
	("&3", "key_replace"),
	("&4", "key_restart"),
	("&5", "key_resume"),
	("kr", "key_right"),
	("&6", "key_save"),
	("&9", "key_sbeg"),
	("&0", "key_scancel"),
	("*1", "key_scommand"),
	("*2", "key_scopy"),
	("*3", "key_screate"),
	("*4", "key_sdc"),
	("*5", "key_sdl"),
	("*6", "key_select"),
	("*7", "key_send"),
	("*8", "key_seol"),
	("*9", "key_sexit"),
	("kF", "key_sf"),
	("*0", "key_sfind"),
	("#1", "key_shelp"),
	("#2", "key_shome"),
	("#3", "key_sic"),
	("#4", "key_sleft"),
	("%a", "key_smessage"),
	("%b", "key_smove"),
	("%c", "key_snext"),
	("%d", "key_soptions"),
	("%e", "key_sprevious"),
	("%f", "key_sprint"),
	("kR", "key_sr"),
	("%g", "key_sredo"),
	("%h", "key_sreplace"),
	("%i", "key_sright"),
	("%j", "key_srsume"),
	("!1", "key_ssave"),
	("!2", "key_ssuspend"),
	("kT", "key_stab"),
	("!3", "key_sundo"),
	("&7", "key_suspend"),
	("&8", "key_undo"),
	("ku", "key_up"),
	("ke", "keypad_local"),
	("ks", "keypad_xmit"),
	("l0", "lab_f0"),
	("l1", "lab_f1"),
	("la", "lab_f10"),
	("l2", "lab_f2"),
	("l3", "lab_f3"),
	("l4", "lab_f4"),
	("l5", "lab_f5"),
	("l6", "lab_f6"),
	("l7", "lab_f7"),
	("l8", "lab_f8"),
	("l9", "lab_f9"),
	("Lf", "label_format"),
	("LF", "label_off"),
	("LO", "label_on"),
	("mo", "meta_off"),
	("mm", "meta_on"),
	("ZY", "micro_column_address"),
	("ZZ", "micro_down"),
	("Za", "micro_left"),
	("Zb", "micro_right"),
	("Zc", "micro_row_address"),
	("Zd", "micro_up"),
	("nw", "newline"),
	("Ze", "order_of_pins"),
	("pc", "pad_char"),
	("DC", "parm_dch"),
	("DL", "parm_delete_line"),
	("DO", "parm_down_cursor"),
	("Zf", "parm_down_micro"),
	("IC", "parm_ich"),
	("SF", "parm_index"),
	("AL", "parm_insert_line"),
	("LE", "parm_left_cursor"),
	("Zg", "parm_left_micro"),
	("RI", "parm_right_cursor"),
	("Zh", "parm_right_micro"),
	("SR", "parm_rindex"),
	("UP", "parm_up_cursor"),
	("Zi", "parm_up_micro"),
	("pk", "pkey_key"),
	("pl", "pkey_local"),
	("px", "pkey_xmit"),
	("pn", "plab_norm"),
	("ps", "print_screen"),
	("pO", "prtr_non"),
	("pf", "prtr_off"),
	("po", "prtr_on"),
	("PU", "pulse"),
	("QD", "quick_dial"),
	("RC", "remove_clock"),
	("rp", "repeat_char"),
	("RF", "req_for_input"),
	("r1", "reset_1string"),
	("r2", "reset_2string"),
	("r3", "reset_3string"),
	("cv", "row_address"),
	("sf", "scroll_forward"),
	("sr", "scroll_reverse"),
	("Zj", "select_char_set"),
	("sa", "set_attributes"),
	("Sb", "set_background"),
	("Zk", "set_bottom_margin"),
	("Zl", "set_bottom_margin_parm"),
	("SC", "set_clock"),
	("sp", "set_color_pair"),
	("Sf", "set_foreground"),
	("ML", "set_left_margin"),
	("Zm", "set_left_margin_parm"),
	("MR", "set_right_margin"),
	("Zn", "set_right_margin_parm"),
	("st", "set_tab"),
	("Zo", "set_top_margin"),
	("Zp", "set_top_margin_parm"),
	("wi", "set_window"),
	("Zq", "start_bit_image"),
	("Zr", "start_char_set_def"),
	("Zs", "stop_bit_image"),
	("Zt", "stop_char_set_def"),
	("Zu", "subscript_characters"),
	("Zv", "superscript_characters"),
	("ta", "tab"),
	("Zw", "these_cause_cr"),
	("ts", "to_status_line"),
	("TO", "tone"),
	("u0", "user0"),
	("u1", "user1"),
	("u2", "user2"),
	("u3", "user3"),
	("u4", "user4"),
	("u5", "user5"),
	("u6", "user6"),
	("u7", "user7"),
	("u8", "user8"),
	("u9", "user9"),
	("WA", "wait_tone"),
	("XF", "xoff_character"),
	("XN", "xon_character"),
	("Zx", "zero_motion"),
	("S8", "alt_scancode_esc"),
	("Yv", "bit_image_carriage_return"),
	("Zz", "bit_image_newline"),
	("Xy", "bit_image_repeat"),
	("Zy", "char_set_names"),
	("ci", "code_set_init"),
	("Yw", "color_names"),
	("Yx", "define_bit_image_region"),
	("dv", "device_type"),
	("S1", "display_pc_char"),
	("Yy", "end_bit_image_region"),
	("S2", "enter_pc_charset_mode"),
	("S4", "enter_scancode_mode"),
	("S3", "exit_pc_charset_mode"),
	("S5", "exit_scancode_mode"),
	("Gm", "get_mouse"),
	("Km", "key_mouse"),
	("Mi", "mouse_info"),
	("S6", "pc_term_options"),
	("xl", "pkey_plab"),
	("RQ", "req_mouse_pos"),
	("S7", "scancode_escape"),
	("s0", "set0_des_seq"),
	("s1", "set1_des_seq"),
	("s2", "set2_des_seq"),
	("s3", "set3_des_seq"),
	("AB", "set_a_background"),
	("AF", "set_a_foreground"),
	("Yz", "set_color_band"),
	("YZ", "set_page_length"),
	("MT", "set_tb_margin"),
	("Xh", "enter_horizontal_hl_mode"),
	("Xl", "enter_left_hl_mode"),
	("Xo", "enter_low_hl_mode"),
	("Xr", "enter_right_hl_mode"),
	("Xt", "enter_top_hl_mode"),
	("Xv", "enter_vertical_hl_mode"),
	("sA", "set_a_attributes"),
	("sL", "set_pglen_inch"),
];

fn main() {
	let path = Path::new(&env::var("OUT_DIR").unwrap()).join("names.rs");
	let mut file = BufWriter::new(File::create(&path).unwrap());

	write!(&mut file, "pub static BOOLEAN: ::phf::Map<u16, &'static str> = ").unwrap();
	let mut builder = phf_codegen::Map::new();
	for (index, name) in BOOLEAN.iter().enumerate() {
		builder.entry(index as u16, &format!("\"{}\"", name));
	}
	builder.build(&mut file).unwrap();
	write!(&mut file, ";\n").unwrap();

	write!(&mut file, "pub static NUMBER: ::phf::Map<u16, &'static str> = ").unwrap();
	let mut builder = phf_codegen::Map::new();
	for (index, name) in NUMBER.iter().enumerate() {
		builder.entry(index as u16, &format!("\"{}\"", name));
	}
	builder.build(&mut file).unwrap();
	write!(&mut file, ";\n").unwrap();

	write!(&mut file, "pub static STRING: ::phf::Map<u16, &'static str> = ").unwrap();
	let mut builder = phf_codegen::Map::new();
	for (index, name) in STRING.iter().enumerate() {
		builder.entry(index as u16, &format!("\"{}\"", name));
	}
	builder.build(&mut file).unwrap();
	write!(&mut file, ";\n").unwrap();

	write!(&mut file, "pub static ALIASES: ::phf::Map<&'static str, &'static str> = ").unwrap();
	let mut builder = phf_codegen::Map::new();
	for &(name, value) in ALIASES {
		builder.entry(name, &format!("\"{}\"", value));
	}
	builder.build(&mut file).unwrap();
	write!(&mut file, ";\n").unwrap();
}
